git:
    resource: "@GitBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
homepage:
    path: /
    defaults:
        _controller: FOSUserBundle:Security:login