<?php

namespace GitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GitRepository extends EntityRepository
{
	public function getByGitUser($gitUser)
	{
		$query = $this->createQueryBuilder('c')
			->where('c.repositoryOwner = :repositoryOwner')
			->setParameter('repositoryOwner', $gitUser)
		;
		
		return $query->getQuery()->getResult();
	}
}
