<?php

namespace GitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GitRepository extends EntityRepository
{
}
